data:
  csv_path: "/content/data/surprise_events1.csv"
  h5_path: "/content/data/surprise_task1.h5"
  train_ids_file: "/content/drive/MyDrive/Colab Notebooks/data/train_ids.txt"
  val_ids_file:   "/content/drive/MyDrive/Colab Notebooks/data/val_ids.txt"
  test_ids_file:  "/content/drive/MyDrive/Colab Notebooks/data/test_ids.txt"
  resize_to: [384, 384]
  in_frames: 12
  out_frames: 12
  stride: 12
  do_normalize: True

model:
  in_channels: 1          
  in_time: 24             
  height: 384
  width: 384
  hidden_dim: 16           

training:
  device: "cuda"           
  batch_size: 10
  lr: 0.0001
  epochs: 10
  ckpt_dir: "outputs/task1a/checkpoints"

inference:
  output_dir: "outputs/task1a/predictions"
