
data:
  csv_path: "/content/data/surprise_events2.csv"
  h5_path: "/content/data/surprise_task2.h5"
  train_ids_file: "/content/drive/MyDrive/Colab Notebooks/data/train_ids.txt"
  val_ids_file: "/content/drive/MyDrive/Colab Notebooks/data/val_ids.txt"
  test_ids_file: "/content/drive/MyDrive/Colab Notebooks/data/test_ids.txt"
  resize_to: [384, 384]
  in_frames: 36
  out_frames: 36
  stride: 36
  do_normalize: False

model:
  in_channels: 3
  height: 384
  width: 384
  hidden_dim: 32

training:
  device: "cpu" 
  batch_size: 2
  lr: 0.0001
  epochs: 10
  ckpt_dir: "outputs/task4/checkpoints"

inference:
  output_dir: "outputs/task4/predictions"
