
data:
  csv_path: "/content/drive/MyDrive/acds-storm-data/events.csv"
  h5_path: "/content/drive/MyDrive/acds-storm-data/train.h5"
  train_ids_file: "/content/drive/MyDrive/acds-storm-data/train_ids.txt"
  val_ids_file: "/content/drive/MyDrive/acds-storm-data/val_ids.txt"
  test_ids_file: "/content/drive/MyDrive/acds-storm-data/test_ids.txt"
  resize_to: [384, 384]
  # in_frames: 12
  # out_frames: 12
  # stride: 6
  do_normalize: True

model:
  in_channels: 3  # Number of input channels (vis, ir069, ir107)
  in_time: 36
  height: 384
  width: 384
  hidden_dim: 32

training:
  device: "cuda"  # or "cpu"
  batch_size: 32
  lr: 0.001
  epochs: 20
  ckpt_dir: "/content/drive/MyDrive/acds-storm-data/package_outputs"

inference:
  mvn_mean_dir: "/content/drive/MyDrive/acds-storm-data/mvn_mean.csv"
  mvn_cov_dir: "/content/drive/MyDrive/acds-storm-data/mvn_cov.csv"
  output_dir: "/content/drive/MyDrive/acds-storm-data/package_outputs"
